// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 757b173b34db14bc23c7b53a15252628add4f815

package data

// linguist's commit from which files were generated.
var LinguistCommit = "757b173b34db14bc23c7b53a15252628add4f815"
