// Code generated by github.com/go-enry/go-enry/v2/internal/code-generator DO NOT EDIT.
// Extracted from github/linguist commit: 971e152fabca12e0ad386833eecb7b15e312a09f

package data

// linguist's commit from which files were generated.
var LinguistCommit = "971e152fabca12e0ad386833eecb7b15e312a09f"
